
### 회원가입(고객)
POST http://localhost:8080/signup/customer
Content-Type: application/json

{
  "email": "floweronwall31@gmail.com",
  "password": "1111",
  "name": "Park",
  "confirmPassword": "1111",
  "phone": "010-1111-2222",
  "registerNumber": "123456-1234567"
}


### 회원가입 인증(고객)
PUT http://localhost:8080/signup/customer/verify?email=floweronwall31@gmail.com&code=G9VxXCDUCF
Content-Type: application/x-www-form-urlencoded


### 로그인(고객)
POST http://localhost:8080/signin/customer
Content-Type: application/json

{
  "email": "floweronwall31@gmail.com",
  "password": "1111"
}


### 정보 조회(고객)
GET http://localhost:8080/info/customer
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6IkNVU1RPTUVSIiwic3ViIjoicFJMWU55YnM4RjhMOWVVWWRSL1J6QT09LjRFaXdHb1poSGFQdWxTUXF0ZHNHZWdyMUNPb2pwby9iNkV2R1ZtdW5YQkE9IiwianRpIjoicFJMWU55YnM4RjhMOWVVWWRSL1J6QT09LkF5RzgyTS9YTVNqRlcxYUxuT01PaGc9PSIsImlhdCI6MTcxNzg0NzczOSwiZXhwIjoxNzE3ODUxMzM5fQ.nG-2cpMEScUy8a2eLNPxuuNbzXmqtnIcs8vs6fI9C_8Q2Vy0ouB2_XuW-eH1zEny

### 상점 검색(비회원)
GET http://localhost:8081/search?keyWord=b

### 자동 검색어
GET http://localhost:8081/search/search/autocomplete?
    keyWord=b

### 회원탈퇴 (고객)
DELETE http://localhost:8080/withdrawal/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6IkNVU1RPTUVSIiwic3ViIjoicFJMWU55YnM4RjhMOWVVWWRSL1J6QT09LjRFaXdHb1poSGFQdWxTUXF0ZHNHZWdyMUNPb2pwby9iNkV2R1ZtdW5YQkE9IiwianRpIjoicFJMWU55YnM4RjhMOWVVWWRSL1J6QT09LkF5RzgyTS9YTVNqRlcxYUxuT01PaGc9PSIsImlhdCI6MTcxNzg0NzczOSwiZXhwIjoxNzE3ODUxMzM5fQ.nG-2cpMEScUy8a2eLNPxuuNbzXmqtnIcs8vs6fI9C_8Q2Vy0ouB2_XuW-eH1zEny

{
  "email": "floweronwall31@gmail.com",
  "password": "1111"
}