spring:
  application:
    name: store
  profiles:
    include: common-domain
  data:
    redis:
      port: 6379
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081
  shutdown: graceful

user-api:
  feign:
    client:
      url: http://localhost:8080

