
server:
  port: 8081
  shutdown: graceful

user-api:
  feign:
    client:
      url: http://localhost:8080
spring:
  profiles:
    include: common-domain

  mvc:
    path-match:
      matching-strategy: ant_path_matcher