
### 상점 검색(비회원)
GET http://localhost:8081/search?keyWord=b

### 자동 검색어
GET http://localhost:8081/search/search/autocomplete?
    keyWord=b

### 대기 예약 추가 (고객)
###
POST http://localhost:8081/waiting/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6IkNVU1RPTUVSIiwic3ViIjoiQUJnOWxwVjRsYkVGRktRQTUzNWJHZz09LjRYR0xyK3dyOUFIbUZ5K3ExL0RSNXhFZDkwM3lOcENWOFZab3FsOXNGTXM9IiwianRpIjoiQUJnOWxwVjRsYkVGRktRQTUzNWJHZz09Lm1GKzBvOGVCS3RHTnVhdmxKZVNLU2c9PSIsImlhdCI6MTcxNzg5ODMzMiwiZXhwIjoxNzE3OTAxOTMyfQ.vjSLkZKBK43_uyEc52w_Loq4B7nJPJ9trdcYeU5D-s4YDSgrVBZtCQCHwyYLBcgL

{
  "storeId": 1,
  "customerId": 2,
  "customerName": "Park",
  "customerEmail": "floweronwall31@gmail.com",
  "customerPhone": "010-1111-2222",
  "reserveTime": "2024-06-10T10:16"
}

### 대기 예약 확인 (고객)
PUT http://localhost:8081/waiting/confirm?
    storeId=1&
    name=Park&
    phone=010-1111-2222
Content-Type: application/x-www-form-urlencoded