
### 대기 예약 추가 (고객)
POST http://localhost:8081/waiting/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6IkNVU1RPTUVSIiwic3ViIjoiWi9JcXZCNERSdE9EVHU3eXQvRWhYZz09LjFqVEhPSlpsdW5iSzlqNFJPSXJhd1ZJQWFrUnhDRTFNYjRGMFh6ZVBxQjQ9IiwianRpIjoiWi9JcXZCNERSdE9EVHU3eXQvRWhYZz09LnNrTFdFaG1LYlNud3IrT21YWGJrTlE9PSIsImlhdCI6MTcxNzgwODEyMywiZXhwIjoxNzE3ODExNzIzfQ.Gvj9IJXDXtecd9Zex9UgD-xCd4Z3qtSjCXeYYyCRUs1LFGPVhEfNsBGQX7ySANnE

{
"storeId": 1,
"customerName": "Lee",
"customerEmail": "floweronwall31@gmail.com",
"customerPhone": "010-1111-2222",
"storeName": "bbbccc",
"latitude": 30.11,
"longitude": 120.11,
"storePhone": ""
}

### 대기 예약 확인 (고객)
PUT http://localhost:8081/waiting/confirm?
    storeId={{$random.integer(100)}}&
    name={{$random.alphanumeric(8)}}&
    phone={{$random.alphanumeric(8)}}
    Content-Type: application/x-www-form-urlencoded