spring:
  application:
    name: store
  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtcHJvamVjdC1kaXZpZGVuZAo=

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        ejb:
          interceptor: org.hibernate.envers.event.spi.EnversIntegrator
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: store
      password: store
    url: jdbc:mysql://localhost:3306/store

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher